name: Gradle build and test (+ coverage)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
        env:
          ORG_GRADLE_PROJECT_token: ${{ secrets.REGISTRY_TOKEN }}
          ORG_GRADLE_PROJECT_user: ${{ secrets.REGISTRY_USER }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Retrieve current version number before release
        run: ./gradlew printVersion

      - name: Release Version
        run: ./gradlew releaseVersion --no-commit

      - name: Push new tag
        run: |
          git push origin --tags

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          version=$(git describe --tags --abbrev=0)
           ./gradlew -q printChangeLog | gh release create $tag -d -t "Release $version" -F - --target main